### ISSUE TITLE
Only the ring is changing

### ISSUE THREAD

**Issue by HarlemSquirrel** [gfduszynski/cm-rgb#5]
Currently, I'm only able to control the ring LEDs. The other commands seem to have no effect. 

```yaml
interface_number : 0
manufacturer_string : Cooler Master Technology Inc.
path : b'0001:0003:00'
product_id : 81
product_string : AMD SR4 lamplight Control
release_number : 264
serial_number :
usage : 0
usage_page : 0
vendor_id : 9494

interface_number : 1
manufacturer_string : Cooler Master Technology Inc.
path : b'0001:0003:01'
product_id : 81
product_string : AMD SR4 lamplight Control
release_number : 264
serial_number :
usage : 0
usage_page : 0
vendor_id : 9494

interface_number : 2
manufacturer_string : Cooler Master Technology Inc.
path : b'0001:0003:02'
product_id : 81
product_string : AMD SR4 lamplight Control
release_number : 264
serial_number :
usage : 0
usage_page : 0
vendor_id : 9494
```
